### ISSUE TITLE
Alert, Name File Upload Corrigindo CSS

### ISSUE THREAD

**Issue by nwyan** [IBTI-Brasilia/Federal-Tax#24]
- [x] Adicionar alerta de validação do arquivo

- [x] Ajustar erro de nome do arquivo

- [x] Corrigir detalhes do CSS em cada página

**Comment by fabiobuiati** [comment]
- [ ] Implementar o Crispy
- [ ] Colocar o username no canto superior direito (puxando do Django Admin)
- [ ] Lembrar de ativar o login

**Comment by francocamila** [comment]
Ao invés de usar o crispy, conseguimos contornar o problema do forms de outra forma.
